add property is_border_required
modelflat/zbl pull request #4
Opened 2024-05-16 08:28 UTC by Elypha

hi,

thanks for your project

I hope this closes https://github.com/modelflat/zbl/issues/3

2024-05-16 08:33 UTC, Elypha commented
also if I may suggest to rename the other property `capture_cursor` to `is_cursor_capture_enabled`,
since if this project will remain largely a wrapper/extension around the `Windows.Graphics.Capture` API, it might be better to just keep their names from the original API

2024-05-18 12:55 UTC, modelflat commented
@Elypha Hi, thanks for contributing! Couple of notes:
- I'm on board with renaming `capture_cursor` - good call!
- Examples won't compile after the change - could you please adjust them accordingly? (ideally we should move to use builder pattern to avoid such breaking changes in the future, but let's leave this for another time for now)
- The change doesn't really work for me. I'm on Windows 10 and am getting:
```
failed to initialize capture: Error { code: HRESULT(0x80004002), message: "No such interface supported" }
```
irrespective of whether I set `is_border_required` to true or false. Not sure what the root cause is. Does it work for you?

2024-05-18 13:20 UTC, Elypha commented
@modelflat thanks for the feedback!

I'm trying to fix the examples in [`98654ce` (#4)](https://github.com/modelflat/zbl/pull/4/commits/98654cedd07ca2a8ec4e02f6900a40f3101e49c3) and hope they are working

For the capture init error, it seems like args are not passed to the constructor properly but I'm not very familiar with rust so I'm likely mistaken.
I'm using the Python lib and it works great. My machine runs Windows 11 22H2 and Python 3.12, and here's a dev build if you are interested to test it x
[dist.zip](https://github.com/modelflat/zbl/files/15364814/dist.zip)

2024-05-18 13:31 UTC, Elypha commented
wait I asked mr gpt and the error code indicates something related to the os api
then I checked the MS api manual, and yes, the border option is not supported in some versions in windows 10: https://learn.microsoft.com/en-gb/uwp/api/windows.graphics.capture.graphicscapturesession?view=winrt-19041

2024-05-18 16:09 UTC, modelflat requested changes
Yup, this seems to be unsupported on the Windows version I'm on. Let's proceed with this change - just a couple of fixes and it should be ready to go!

2024-05-18 16:09 UTC, modelflat commented on zbl/src/capture/mod.rs
> +        session.SetIsBorderRequired(is_border_required)?;
Let's account for the possibility of this not being supported with a meaningful error message. Something like this should work:

```suggestion
        if !is_border_required {
            if let Err(e) = session.SetIsBorderRequired(is_border_required) {
                log::warn!(
                    "got '{}' when trying to disable the capture border - see https://github.com/modelflat/zbl/pull/4 for more info",
                    e
                );
            }
        }
```

2024-05-18 16:09 UTC, modelflat commented on zbl_py/zbl/__init__.py
> +            is_border_required=args.is_border_required,
Let's also update the args in `zbl_py/zbl/__main__.py` for the CLI tool.

2024-05-18 16:51 UTC, Elypha commented
great, can you test if all the changes work now

2024-05-18 18:04 UTC, modelflat requested changes
Almost there - let's just change the default value for the `IsBorderRequired` to mirror the WGC API default (`true`)

2024-05-18 18:04 UTC, modelflat commented on zbl/examples/directx_interop.rs
> +        opencv::core::initialize_context_from_d3d11_device(&capture.d3d.device)
```suggestion
        opencv::core::initialize_context_from_d3d11_device(&mut capture.d3d.device)
```

2024-05-18 18:04 UTC, modelflat commented on zbl_py/src/lib.rs
> +        let is_border_required = is_border_required.unwrap_or(false);
I think we should change the default to be `true` (and in the Python version as well) to mirror the WGC API.

2024-05-19 04:05 UTC, Elypha commented
sorry microsoft /j
the default values in the rust constructor and python lib are updated

2024-05-19 12:22 UTC, merged

2024-05-19 12:23 UTC, modelflat commented
Merged! Thank you so much for your contribution ❤️